apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: nginx-transfomr
spec:
  components:
    - name: nginx-comp
      type: webservice
      properties:
        image: nginx:1.14.2
        ports:
          - port: 80
            expose: true
      traits:
        - type: log-transformer
          properties:
            type: apache
            sample
